baseurl: https://www.mariocarrion.com
disablePathToLower: true
languageCode: en-us
title: Mario Carrion
indexes: {}
enableEmoji: true
contentdir: "content"
rssLimit: 15

pygmentsUseClassic: true

permalinks:
  blog: "blog/:slug/"

menu:
  main:
   - name: "About"
     weight: -120
     identifier: "about"
     url: "/about.html"
   - name: "All Posts"
     weight: -110
     identifier: "archive"
     url: "/archive.html"
   - name: "Books"
     weight: -100
     identifier: "books"
     url: "/books.html"
   - name: "Resume"
     weight: -90
     identifier: "resume"
     url: "https://docs.google.com/document/d/1i0W6qNfGMhTfwWTHBaaKzlN9HLGwbk3GLeh8VtVlhNM"


params:
  include_rss: true
  latestpostscount: 35
  author: "Mario Carrion"
  dateform: "Jan 02, 2006"
  dateformfull: "Mon Jan 2 2006 15:04:05 MST"
  github: "//github.com/MarioCarrion"
  twitter: "//twitter.com/MarioCarrion"
  linkedin: "//linkedin.com/in/MarioCarrion"
  faviconfile: "favicon.png"
