name = "Lagom"
license = "MIT"
description = ""
homepage = "http://www.mariocarrion.com/"
min_version = 0.17
pygmentsuseclasses = true

[author]
  name = "Mario Carrion"
  homepage = "http://www.mariocarrion.com/"

[original]
  name = "Lagom"
  homepage = "https://github.com/swanson/lagom"
  repo = "https://github.com/swanson/lagom"
