name = "Lagom"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://www.mariocarrion.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Mario Carrion"
  homepage = "http://www.mariocarrion.com/"

[original]
  name = "Lagom"
  homepage = "https://github.com/swanson/lagom"
  repo = "https://github.com/swanson/lagom"
